### PR TITLE
crash-fix thread-safe function round trip example

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes an access-after-free and a memory leak.

Closes: https://github.com/gabrielschulhof/abi-stable-node-addon-examples/pull/1

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
@amissine can you please grab [this branch](https://github.com/gabrielschulhof/abi-stable-node-addon-examples/tree/1-tsfn_round_trip) and verify that it does not segfault? Neither should it leak native `ThreadItem` structures.

**Comment by gabrielschulhof** [comment]
@amissine I also updated the comments to make them more detailed.

**Comment by amissine** [comment]
Thank you, Gabriel! Having run this JavaScript,
```
  1 const bindings = require('bindings')('round_trip');
  2 const answers = [ false, false, false, false, false, false ];
  3 var i = 0;
  4 
  5 bindings.startThread((item, thePrime) => {
  6   console.log('The prime: ' + thePrime);
  7   
  8   // Answer the call with a 90% probability of returning true somewhere between
  9   // 200 and 400 ms from now.
 10   setTimeout(() => {
 11     var theAnswer = (Math.random() > 0.1);
 12     theAnswer = answers[i++];
 13     console.log(thePrime + ': answering with ' + theAnswer);
 14     bindings.registerReturnValue(item, theAnswer);
 15   }, Math.random() * 200 + 200);
 16 });
```
, I am getting this output:
```
alec@mba ~/product/abi-stable-node-addon-examples/thread_safe_function_round_trip/node-api (1-tsfn_round_trip) $ npm test

> thread_safe_function_round_trip@0.0.0 test /Users/alec/product/abi-stable-node-addon-examples/thread_safe_function_round_trip/node-api
> node index.js

The prime: 7919
The prime: 17389
The prime: 27449
7919: answering with false
17389: answering with false
27449: answering with false
alec@mba ~/product/abi-stable-node-addon-examples/thread_safe_function_round_trip/node-api (1-tsfn_round_trip) $ 
```
No segfaults.
:)

**Comment by gabrielschulhof** [comment]
@amissine thanks a lot for verifying!

**Pull request merged**
